import { IntentId } from '../types.js';

/** Categorized keyword groups used as the canonical matching vocabulary
 * (prompt §5). Each intent maps to a subset; the union is grouped by theme. */
export const KEYWORD_GROUPS = {
  Projects: [
    'create project',
    'new project',
    'post project',
    'start project',
    'edit project',
    'update project',
    'change project',
    'delete project',
    'remove project',
    'cancel project',
    'view project',
    'see project',
    'open project',
    'show project',
    'search project',
    'find project',
    'browse project',
    'look for project',
  ],
  Proposals: [
    'submit proposal',
    'send proposal',
    'apply to project',
    'apply for project',
    'place bid',
    'submit bid',
    'generate proposal',
    'draft proposal',
    'write proposal',
    'proposal draft',
    'create proposal',
  ],
  Profiles: [
    'optimize profile',
    'improve profile',
    'boost profile',
    'build portfolio',
    'create portfolio',
    'add portfolio',
    'build resume',
    'write resume',
    'update resume',
    'create resume',
    'cover letter',
    'write cover letter',
    'generate cover letter',
  ],
  Payments: [
    'pay freelancer',
    'release payment',
    'invoice',
    'payment status',
    'send payment',
    'make payment',
    'escrow',
  ],
  Messages: [
    'send message',
    'message freelancer',
    'message client',
    'contact them',
    'reach out',
    'chat',
    'dm',
  ],
  Contracts: [
    'generate contract',
    'create contract',
    'contract draft',
    'sign contract',
    'plan milestones',
    'set milestones',
    'add milestone',
    'schedule payment',
  ],
  Reviews: [
    'write review',
    'leave review',
    'rate freelancer',
    'rate client',
    'add review',
    'review feedback',
  ],
  Admin: [
    'report scam',
    'report fraud',
    'scam',
    'fraud',
    'open dispute',
    'file dispute',
    'dispute',
    'ban user',
    'block user',
    'moderate',
  ],
  Help: ['help', 'help me', 'how do i', 'what is', 'support', 'guide', 'assist', 'platform help'],
  Knowledge: [
    'search knowledge',
    'search articles',
    'knowledge base',
    'learn about',
    'documentation',
    'faq',
  ],
} as const;

/** Per-intent keyword sets used to build rules (prompt §4). */
export const INTENT_KEYWORDS: Readonly<Record<IntentId, readonly string[]>> = {
  [IntentId.UNKNOWN]: [],
  [IntentId.CREATE_PROJECT]: ['create project', 'new project', 'post project', 'start project'],
  [IntentId.UPDATE_PROJECT]: ['edit project', 'update project', 'change project'],
  [IntentId.DELETE_PROJECT]: ['delete project', 'remove project', 'cancel project'],
  [IntentId.VIEW_PROJECT]: ['view project', 'see project', 'open project', 'show project'],
  [IntentId.SEARCH_PROJECTS]: [
    'search project',
    'find project',
    'browse project',
    'look for project',
  ],
  [IntentId.SUBMIT_PROPOSAL]: [
    'submit proposal',
    'send proposal',
    'apply to project',
    'apply for project',
    'place bid',
    'submit bid',
  ],
  [IntentId.GENERATE_PROPOSAL]: [
    'generate proposal',
    'draft proposal',
    'write proposal',
    'proposal draft',
    'create proposal',
  ],
  [IntentId.OPTIMIZE_PROFILE]: ['optimize profile', 'improve profile', 'boost profile'],
  [IntentId.BUILD_PORTFOLIO]: ['build portfolio', 'create portfolio', 'add portfolio'],
  [IntentId.BUILD_RESUME]: ['build resume', 'write resume', 'update resume', 'create resume'],
  [IntentId.GENERATE_COVER_LETTER]: ['cover letter', 'write cover letter', 'generate cover letter'],
  [IntentId.MATCH_PROJECT]: ['match project', 'find best match', 'recommend project'],
  [IntentId.CAREER_ADVICE]: ['career advice', 'career guidance', 'career help'],
  [IntentId.GENERATE_CONTRACT]: [
    'generate contract',
    'create contract',
    'contract draft',
    'sign contract',
  ],
  [IntentId.PLAN_MILESTONES]: [
    'plan milestones',
    'set milestones',
    'add milestone',
    'schedule payment',
  ],
  [IntentId.GENERATE_REVIEW]: [
    'write review',
    'leave review',
    'rate freelancer',
    'rate client',
    'add review',
  ],
  [IntentId.REPORT_SCAM]: ['report scam', 'report fraud', 'scam', 'fraud'],
  [IntentId.OPEN_DISPUTE]: ['open dispute', 'file dispute', 'dispute'],
  [IntentId.SEND_MESSAGE]: [
    'send message',
    'message freelancer',
    'message client',
    'contact them',
    'reach out',
    'chat',
    'dm',
  ],
  [IntentId.SEARCH_KNOWLEDGE]: [
    'search knowledge',
    'search articles',
    'knowledge base',
    'learn about',
    'documentation',
    'faq',
  ],
  [IntentId.PLATFORM_HELP]: [
    'help',
    'help me',
    'how do i',
    'what is',
    'support',
    'guide',
    'assist',
  ],
  [IntentId.ADMIN_ACTION]: ['ban user', 'block user', 'moderate'],
  [IntentId.SYSTEM]: [],
};
